### ISSUE TITLE
Daily Estimated Earnings in 2.0.0.4

### ISSUE THREAD

**Issue by wewuzkingz** [nicehash/NiceHashMiner2#40] opened 2017-05-26 02:38 UTC
The daily estimated earnings is only showing the DEE for my CPU mining and not my GPU.  The status page for my mining does report the mining, though.

**Comment by wewuzkingz** [comment] 2017-05-26 02:45
I should add that under Mining Details *it was showing the GPU speed and BTC/day* information.

**Comment by wewuzkingz** [comment] 2017-05-26 03:04
So, it appears to be happening only using CC Miner 1.7.6.  It switched to something else and the DEE showed up again, including in mining details.  But then it switched back to CC Miner and the DEE went back to only showing the CPU estimate.

**Comment by ChriscomIT** [comment] 2017-05-26 03:31
Same here. Mostly CCminer at starting throws an error message "failed to bind api -1" and then it don't show the mining speed and DEE. But sometimes it restarts randomly without the error message and then the speed for GPU mining is shown as well as the DEE. 

Same goes for excavator and equihash but here it seems that the port changes at the random restart and then mining speed and DEE will be shown in the GUI. 

However, the payout is not affected at all from this as the mining is working normally.

**Comment by S74nk0** [comment] 2017-05-30 10:10
@wewuzkingz @ChriscomIT Yes this is a known bug and is fixed in v2.0.0.5. We will be releasing it soon.

**Comment by S74nk0** [comment] 2017-05-30 13:01
NiceHash Miner **v2.0.0.5 Alpha RAD** is released (has [excavator v1.2.4a](https://github.com/nicehash/excavator/releases) integrated - for now NVIDIA only) and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually (keep link private please).
Closing...
Reopen if issue is present in **v2.0.0.5 Alpha RAD**

**Comment by ChriscomIT** [comment] 2017-06-02 13:59
The issue is present in some sort also with 2.0.0.5 mainly with xmr miner and DEE values.

**Comment by S74nk0** [comment] 2017-06-15 21:44
NiceHash Miner **v2.0.0.7 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.7 Alpha**

**Closed as completed by S74nk0** 2017-06-15 21:44 UTC
