### ISSUE TITLE
Excavator doesn't close when switching to different algo, and crashes when window resizing.

### ISSUE THREAD

**Issue by DaPsyCho** [nicehash/NiceHashMiner2#72] opened 2017-06-10 23:24 UTC
using Nicehash Miner 2.0.0.6,

I noticed that even though ccminer opened and was mining lyra, excavator window was open, and upon trying to resize it crashed, and reopened. This did not seem to affect Lyra mining performance however.

**Comment by Squall-Leonhart** [comment] 2017-06-12 09:15
excavator is meant to stay open.

**Comment by S74nk0** [comment] 2017-06-12 10:32
@DaPsyCho this is intended behavior. When mining **excavator** will always be opened and ready to get new instructions what to mine what to stop mining etc. When **excavator** closes for some reason a restart will be made. 
Please make clear what were you trying to resize and what did crash?

**Comment by DaPsyCho** [comment] 2017-06-12 14:30
http://imgur.com/67yqKdO <- screenshot right before crash.

I moved excavator window as such^ (to screenshot) and all the text disappeared, I tried to resize it and move it to find the text but then the excavator window crashed. Lyra kept on mining as normal though.

**Comment by S74nk0** [comment] 2017-06-15 21:47
NiceHash Miner **v2.0.0.7 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.7 Alpha**

**Closed as completed by S74nk0** 2017-06-15 21:47 UTC
