### ISSUE TITLE
v2.0.0.8 AMD "DisableAMDTempControl": true, Doesn't Work?

### ISSUE THREAD

**Issue by UCDHIUS** [nicehash/NiceHashMiner2#132] opened 2017-07-09 04:44 UTC
I would like to control GPU fans manually with MSI Afterburner but v2.0.0.8 won't let me?

If I set fan speed with AB and then launch v2.0.0.8 it will automatically control fan speed.. 

Any help?

**Comment by Crypto-Lord** [comment] 2017-07-09 14:32
I'm having the same issue where I set 95% fan speed in AB and in NHMv2.0.0.8 it changes them instantly to 0% when starting mining. Resulting in temps to skyrocket & overheat. (Limited temps in AB, but still need a fix) Uploading recent log which may help find the root cause.
Also it appears to be affecting AMD only, my gtx 1080 is unaffected (when it's mining).

[log.txt](https://github.com/nicehash/NiceHashMiner2/files/1133806/log.txt)

**Comment by Erwin73** [comment] 2017-07-09 16:09
Have also trouble with TempControl with my AMD cards

**Comment by UCDHIUS** [comment] 2017-07-09 22:02
@Crypto-Lord same exact issue i'm experiencing.

**Comment by Crypto-Lord** [comment] 2017-07-09 22:45
They posted this on twitter about it:
 'This is not a bug but a feature. Excavator keeps the AMD GPU warm enough so that hardware acceleration would be stable.'
https://twitter.com/NiceHashMining/status/884071536965058561
I've put a limit on the temps to prevent overheating. I really don't like running my gpus at high temps

**Comment by ghost** [comment] 2017-07-10 01:18
keeps my gpu running " warm " computer crashes and my fans stop working till I reboot again.

**Comment by UCDHIUS** [comment] 2017-07-10 02:25
@Crypto-Lord 

This needs to be fixed or have the option to disable, my 380X can't maintain stable clocks with v2.0.0.8 and its constantly crashing I can't even maintain 900/1100 

v2.0.0.7 and 1.7.5.13  I can run 1030/1615 no crashing totally stable and stable temps.

**Comment by Crypto-Lord** [comment] 2017-07-10 14:03
I agree that temps have gone through the roof with the lack of fan control. I've limited my GPUs for temps but also started using v1 again. I haven't found a solution for this but I'm just a user, so it's up to the people that made this recent update to address this issue.
It's going to cause a lot of GPUs to have a lower life span and possibly be a fire risk.

**Comment by S74nk0** [comment] 2017-07-31 23:17
This issue is related to [excavator](https://github.com/nicehash/excavator/issues) with AMD fans. This issue should hopefully be fixed with [1.2.11 alpha](https://github.com/nicehash/excavator/releases/tag/v1.2.11a) and it will be included in the upcoming nhm v2.0.0.9.

Closing issue... issue related to [excavator](https://github.com/nicehash/excavator)

**Closed as completed by S74nk0** 2017-07-31 23:17 UTC
