### ISSUE TITLE
starting excavator_server BSOD @phymem.sys

### ISSUE THREAD

**Issue by t3t3** [nicehash/NiceHashMiner2#99] opened 2017-06-21 05:32 UTC
win7 ent x64, 3x gtx 980; basic (intel) system with no fancy drivers or other stuff installed, except: evga precisionx, anydesk (ex teamviewer) and imdisk (a ramdisk driver); bsod happens whether the latter apps (or their services if applicable) are running or not. nothing else going on, apart from most basic os services.

this happened during nicehash miner update process, and from then on this repeated over and over again (including file downloads), since apparently the update won't ever finish, or at least can't write some tags to its settings file, because of the crash.

**countermeasure**: "disable" phymem.sys by completely locking it away (deny any access to registry keys and the file itself). this prevents the bsod, since nicehash miner can't replace the file and/or the registry keys, nor start the service, and now excavator_server starts; mining seems to work...

**Comment by nicehashdev** [comment] 2017-06-21 09:27
There is no need for phymem.sys if you have NVIDIA only (as you do, by the looks of specs).

Can you open device manager and show us your display adapters? Do you have anything else there besides NVIDIA cards?

**Comment by vasyapupkin1** [comment] 2017-06-21 09:43
But I have AMD...

**Comment by t3t3** [comment] 2017-06-21 10:18
i have read that it's only for amd, that's why i tried to enforce it to sit quiet by denying any access to the file and reg keys, even when excavator_server (apparently) tries to start that driver (which is initially set to mode 3/"start on demand" as far i can tell).

apart from the nv's there is the onboard intel hd 3000, activated and also set as active display gpu. maybe because of that? still need a screenshot? just fyi: never had any amd drivers installed on the system.

**Comment by vasyapupkin1** [comment] 2017-06-21 11:23
I also have intel hd graphics. I uninstall drivers and disable IGFX in BIOS. No effect. BSOD and restart or like there http://www.21nn.ru/2012/04-3/tv_pomexi.jpg
[log1.txt](https://github.com/nicehash/NiceHashMiner2/files/1091315/log1.txt)

**Comment by t3t3** [comment] 2017-06-21 11:53
have used nirsoft driverview to list all active non-microsoft drivers along with their versions - maybe it helps to narrow down possible causes:
![drivers](https://user-images.githubusercontent.com/13648654/27382882-f846bf8e-5688-11e7-9725-6993eb316463.PNG)

**Comment by nerdatwork** [comment] 2017-06-21 12:22
Facing same BSOD for miner. Why does NHM2 keeps downloading on every run  though ?

**Comment by vasyapupkin1** [comment] 2017-06-21 12:32
>t3t3
All non-microsoft drivers:
![drv](https://user-images.githubusercontent.com/29598026/27384133-7832a502-5696-11e7-968c-097b76bee097.png)

**Comment by t3t3** [comment] 2017-06-21 12:35
@vasyapupkin1: we both use imdisk. i have no idea what phymem.sys in particular does, but since it sounds so memory-ish, imdisk might be a candidate?

**Comment by vasyapupkin1** [comment] 2017-06-21 12:47
No virual imdisk is created. Total RAM is 12Gb, 7Gb is free. 
I think, probably excavator try to use improper overclock values and system crashes.

**Comment by t3t3** [comment] 2017-06-21 13:00
you might still try to completely unload the imdisk driver;

anyway overclocking can't be the reason in my case, i guess, since, if i'm right, phymem.sys should do nothing when only nv cards are present, and since i locked the file away, excavator starts (and works) without crashing.

also i guess a hardware related crash (because of oc'ing) would not result in a bsod that directly points to phymem.sys, but rather to the particular low level driver...

**Comment by vasyapupkin1** [comment] 2017-06-21 13:22
I blocked folder "excavator_server" and it launchs. Run benchmark and start mining. RX460 on dagger hashimoto works as on 1.7.5.13.  - avg 11.8 MH/s. BUT!!! no visible statistics (neither cryptonight nor dagger, and online too).
So if result is the same... no need to update. I deleted it and returned to 1.7.5.13.
![without_excavator](https://user-images.githubusercontent.com/29598026/27386142-93704caa-569d-11e7-9891-479c0dd20eed.png)
. 
As for me the question is closed till a better day

**Comment by phr34k0** [comment] 2017-06-21 22:40
Same. Received a BSOD on Win 7 x64 while installing Nicehash 2.0. Reverted back to old version. Might be due to their cert signing or whatever to phymem.sys. I suggest staying away from this update till it's stable. Not sure why the guys even replaced the website to a new layout with lack of stability and optimization both site and software >_>

**Comment by Squall-Leonhart** [comment] 2017-06-22 22:51
please attach the dump files in relation to these bsods.

**Comment by t3t3** [comment] 2017-06-23 07:05
minidump (zip upload didn't work for some reason): 
[062117-62384-01.dmp.txt](https://github.com/nicehash/NiceHashMiner2/files/1097000/062117-62384-01.dmp.txt)

**Comment by Squall-Leonhart** [comment] 2017-06-23 08:32
the developer of this driver needs to check his code

breakpoints are not permitted in kernel mode drivers.

this needs to be reproduced in a system set up with the kernel in debugging mode.

**Comment by phr34k0** [comment] 2017-06-23 12:58
Ah so that's the problem "C : \ U s e r s \ G e r a l d \ A p p D a t a \ R o a m i n g \ n h m 2 \ b i n \ e x c a v a t o r _ s e r v e r \ p h y m e m . s y s" and referring to this https://github.com/nicehash/NiceHashMiner2/issues/79 . Never had problems with the old versions till you guys decide to include excavator_server together with 2.0. It's unstable, kill it.

**Comment by S74nk0** [comment] 2017-06-29 17:21
**everyone** we have released a new [excavator_v1.2.9a](https://github.com/nicehash/excavator/releases/tag/v1.2.9a) and it should have this issue fixed. After NiceHash Miner 2.0.0.7 restart it will update excavator to **v1.2.9a**.
Please report if **NiceHash Miner 2.0.0.7** and **excavator v1.2.9a** resolve this issue.

**Comment by vasyapupkin1** [comment] 2017-06-29 21:28
![img_20170630_000144](https://user-images.githubusercontent.com/29598026/27711168-f689cbac-5d2a-11e7-966d-276f360028d7.jpg)

**Comment by vasyapupkin1** [comment] 2017-06-29 22:20
Try to release without overclocking. User can do it by himself.

**Comment by S74nk0** [comment] 2017-07-07 19:31
NiceHash Miner **v2.0.0.8 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.8 Alpha**

**Closed as completed by S74nk0** 2017-07-07 19:31 UTC
