### ISSUE TITLE
[v2.0.0.7 - FIXED] 2.0.0.6 Misreporting Speed when two different algos being mined using same named program

### ISSUE THREAD

**Issue by AngryOverlord** [nicehash/NiceHashMiner2#73] opened 2017-06-11 16:30 UTC
I have a 1070 and a 1080ti in this box and they were mining both using ccminer, but they were running two different versions. The speed from the faster hashrate algo was being displayed on both algos giving wrong information on the mining details and daily estimated earnings section.
![wrong speed](https://user-images.githubusercontent.com/8902047/27012637-b14d43f0-4e90-11e7-89a0-4c6ad2e3c3cf.png)

**Comment by S74nk0** [comment] 2017-06-13 15:38
@AngryOverlord This issue seems to be caused by using the same API read port for lbry. Can you please provide the logs for this case. Best to zip the whole logs folder and send it to me at stanko@nicehash.com.

**Comment by S74nk0** [comment] 2017-06-13 22:03
@AngryOverlord The issue is located and fixed.

**Comment by AngryOverlord** [comment] 2017-06-13 22:37
Apologies for not getting the log sent, I just got home but thank you for finding and resolving the issue quickly!

**Comment by S74nk0** [comment] 2017-06-15 21:43
NiceHash Miner **v2.0.0.7 Alpha** is released and includes **feature**/**bugfix** related to this issue. Expect an update notice in your NHM2 client or download the new version manually.
Closing...
Reopen if issue is present in **v2.0.0.7 Alpha**

**Closed as completed by S74nk0** 2017-06-15 21:43 UTC
Labels: bug
